// <auto-generated />
using FXRatesAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FXRatesAPI.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FXRatesAPI.Domain.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Australian Dollar",
                            Symbol = "AUD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canadian Dollar",
                            Symbol = "CAD"
                        },
                        new
                        {
                            Id = 3,
                            Name = "US Dollar",
                            Symbol = "USD"
                        },
                        new
                        {
                            Id = 4,
                            Name = "British Pound Sterling",
                            Symbol = "GBP"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NZ Dollar",
                            Symbol = "NZD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
